// <auto-generated />
using System;
using EFCoreModelApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreModelApp.Migrations
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20260324234937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EFCoreModelApp.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentID = 2,
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("EFCoreModelApp.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DepartmentID = 1,
                            FirstName = "Aiko",
                            HireDate = new DateTime(2026, 3, 24, 19, 49, 36, 689, DateTimeKind.Local).AddTicks(5054),
                            LastName = "Tanaka"
                        },
                        new
                        {
                            EmployeeID = 2,
                            DepartmentID = 2,
                            FirstName = "Zainab",
                            HireDate = new DateTime(2026, 3, 24, 19, 49, 36, 691, DateTimeKind.Local).AddTicks(1676),
                            LastName = "Al-Farsi"
                        });
                });

            modelBuilder.Entity("EFCoreModelApp.Employee", b =>
                {
                    b.HasOne("EFCoreModelApp.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCoreModelApp.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
